name: Deploy to Vercel
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Trigger Vercel Deploy
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_75J98d092GbKdWBpht6xk8hr2AEE/QJvS8v4TyN